let DATA=null;let movieShown=20;let movieFilter='all';let posterCache=JSON.parse(localStorage.getItem('horrorometro_posters')||'{}');
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fallback(title,sub=''){return `<div class="poster poster-fallback"><div><div style="font-size:.7rem;letter-spacing:.16em;color:#d05a6b;margin-bottom:10px">HORRORÓMETRO</div>${esc(title)}<div style="font-size:.68rem;color:#8a8582;margin-top:9px">${esc(sub)}</div></div></div>`}
async function wikiImage(title){
  const key=title.toLowerCase().replace(/[^a-z0-9áéíóúñ ]/gi,'').trim(); if(posterCache[key]) return posterCache[key];
  const variants=[title.replace(/\s*\([^)]*\)\s*$/,''),title];
  for(const lang of ['es','en']) for(const q of variants){
    try{const u=`https://${lang}.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(q)}&gsrlimit=1&prop=pageimages&piprop=thumbnail&pithumbsize=600&format=json&origin=*`;const r=await fetch(u);const j=await r.json();const pages=j.query?.pages||{};const p=Object.values(pages)[0];const src=p?.thumbnail?.source;if(src){posterCache[key]=src;localStorage.setItem('horrorometro_posters',JSON.stringify(posterCache));return src}}catch(e){}}
  return null;
}
async function hydrateImages(){for(const img of $$('.auto-poster')){const title=img.dataset.title;const src=await wikiImage(title);if(src){img.outerHTML=`<img class="poster auto-poster" loading="lazy" src="${src}" alt="Portada de ${esc(title)}" data-title="${esc(title)}">`}}}
function movieCards(){let arr=[...DATA.movies].filter(m=>movieFilter==='all'||m.tags.includes(movieFilter));const q=$('#search').value.trim().toLowerCase();if(q)arr=arr.filter(m=>m.title.toLowerCase().includes(q));const sort=$('#movieSort').value;arr.sort((a,b)=>sort==='rating'?b.rating-a.rating:sort==='year'?(b.year||0)-(a.year||0):sort==='old'?(a.year||9999)-(b.year||9999):sort==='az'?a.title.localeCompare(b.title,'es'):a.rank-b.rank);const visible=arr.slice(0,movieShown);$('#movieGrid').innerHTML=visible.map(m=>`<article class="movie-card" tabindex="0" data-kind="movie" data-id="${m.id}"><div class="rank-badge">#${m.rank}</div>${fallback(m.title,m.year||'')}<div class="movie-info"><h3>${esc(m.title)}</h3><div class="movie-meta"><span>${m.year||'—'}</span><span class="score">★ ${m.rating.toFixed(1).replace('.0','')}</span></div><div class="tags">${m.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div></article>`).join('');$('#moreMovies').style.display=arr.length>visible.length?'inline-flex':'none';}
function seriesCards(){const s=DATA.series;$('#seriesGrid').innerHTML=s.map(x=>`<article class="series-card" data-series="${esc(x.title)}"><div class="series-top"><div><h3>${esc(x.title)}</h3><p>${esc(x.format)} · ${x.seasons} temporada${x.seasons==1?'':'s'} · ${x.episodes} episodios</p></div>${x.imdb?`<div class="series-score">${Number(x.imdb).toFixed(1)}</div>`:''}</div></article>`).join('');$('#episodeCount').textContent=`${DATA.episodes.length} registros`;$('#episodeList').innerHTML=DATA.episodes.map(e=>`<div class="episode-row"><span>${esc(e.series)}</span><span>S${e.season} · E${e.episode}</span><strong>${esc(e.title)}</strong><span class="episode-rating">★ ${e.imdb??'—'}</span></div>`).join('')}
function creatures(){let a=DATA.creatures.filter(x=>x.rating!==null).sort((x,y)=>y.rating-x.rating);$('#creatureTop').innerHTML=a.slice(0,4).map((c,i)=>`<article class="creature-hero"><div class="eyebrow">#${i+1} · ${esc(c.sourceType)}</div><h3>${esc(c.name)}</h3><div class="bigscore">★ ${c.rating.toFixed(1).replace('.0','')}</div><div class="creature-source">${esc(c.source)}</div></article>`).join('');renderCreatureGrid();}
function renderCreatureGrid(){const q=$('#creatureSearch').value.trim().toLowerCase();const src=$('#creatureSource').value;let a=DATA.creatures.filter(c=>(c.rating!==null)&& (src==='all'||c.sourceType===src) && (!q||`${c.name} ${c.source} ${c.type}`.toLowerCase().includes(q))).sort((x,y)=>y.rating-x.rating);$('#creatureGrid').innerHTML=a.map(c=>`<article class="creature-card"><div class="creature-head"><div><h3>${esc(c.name)}</h3><div class="creature-type">${esc(c.type)}</div></div><div class="score">★ ${c.rating.toFixed(1).replace('.0','')}</div></div><div class="creature-source">${esc(c.source)}${c.segment?` · ${esc(c.segment)}`:''}</div><p class="creature-desc">${esc(c.desc)}</p></article>`).join('')||'<div style="color:#8c8784">No hay criaturas con esa búsqueda.</div>'}
function vhs(){const a=DATA.vhs.filter(x=>x.rating!==null).sort((x,y)=>y.rating-x.rating);$('#vhsGrid').innerHTML=a.map(c=>`<article class="vhs-card"><div class="vhs-movie">${esc(c.movie)} · ${esc(c.segment)}</div><h3>${esc(c.name)}</h3><div class="score">★ ${c.rating.toFixed(1).replace('.0','')}</div><p>${esc(c.desc)}</p></article>`).join('')}
function stats(){const avg=DATA.movies.reduce((s,m)=>s+m.rating,0)/DATA.movies.length;$('#stats').innerHTML=[['91','Películas calificadas'],[avg.toFixed(1),'Media personal'],[String(DATA.creatures.filter(c=>c.rating!==null).length),'Criaturas puntuadas'],[String(DATA.episodes.length),'Episodios de referencia']].map(x=>`<div class="stat"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}
function openMovie(m){$('#dialogBody').innerHTML=`<div class="modal">${fallback(m.title,m.year||'')}<div><div class="modal-label">Puesto #${m.rank}</div><h2>${esc(m.title)}</h2><div class="modal-score">★ ${m.rating.toFixed(1).replace('.0','')} / 10</div><p><strong>Año:</strong> ${m.year||'—'}</p><p><strong>Categorías:</strong> ${m.tags.length?m.tags.join(' · '):'Terror general'}</p><p>Esta es tu calificación personal. Horrorómetro no la modifica ni la sustituye por una puntuación externa.</p></div></div>`;$('#dialogBody').querySelector('.poster')?.classList.add('auto-poster');$('#dialogBody').querySelector('.auto-poster').dataset.title=m.title;$('#dialogBody').querySelector('.auto-poster').src='';$('#dialog').showModal();hydrateImages();}
function openRandom(){const m=DATA.movies[Math.floor(Math.random()*DATA.movies.length)];openMovie(m)}
async function init(){const r=await fetch('data/catalog.json');DATA=await r.json();stats();movieCards();seriesCards();creatures();vhs();hydrateImages();}
$('#search').addEventListener('input',()=>{movieShown=20;movieCards();});$('#movieSort').addEventListener('change',()=>{movieShown=20;movieCards();});$$('.filter-pill').forEach(b=>b.addEventListener('click',()=>{$$('.filter-pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');movieFilter=b.dataset.filter;movieShown=20;movieCards();}));$('#moreMovies').addEventListener('click',()=>{movieShown+=20;movieCards();});$('#focusSearch').addEventListener('click',()=>{$('#search').focus();location.hash='peliculas'});$('#randomBtn').addEventListener('click',openRandom);$('#creatureSearch').addEventListener('input',renderCreatureGrid);$('#creatureSource').addEventListener('change',renderCreatureGrid);$('#closeDialog').addEventListener('click',()=>$('#dialog').close());$('#movieGrid').addEventListener('click',e=>{const c=e.target.closest('.movie-card');if(!c)return;openMovie(DATA.movies.find(m=>m.id===c.dataset.id))});init();